// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/device_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 861110254133854312),
      name: 'DeviceEntity',
      lastPropertyId: const obx_int.IdUid(8, 6710299167213865616),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 597514898662851586),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8723696582219747134),
            name: 'uniqueDeviceId',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(1, 767293445575446884)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7623059609342789997),
            name: 'deviceName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7504549426938232851),
            name: 'statusName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7108638476595533374),
            name: 'capabilitiesJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2478131308966573234),
            name: 'telemetryJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 273300460829165690),
            name: 'localIp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6710299167213865616),
            name: 'authToken',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 861110254133854312),
      lastIndexId: const obx_int.IdUid(1, 767293445575446884),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DeviceEntity: obx_int.EntityDefinition<DeviceEntity>(
        model: _entities[0],
        toOneRelations: (DeviceEntity object) => [],
        toManyRelations: (DeviceEntity object) => {},
        getId: (DeviceEntity object) => object.id,
        setId: (DeviceEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceEntity object, fb.Builder fbb) {
          final uniqueDeviceIdOffset = fbb.writeString(object.uniqueDeviceId);
          final deviceNameOffset = fbb.writeString(object.deviceName);
          final statusNameOffset = fbb.writeString(object.statusName);
          final capabilitiesJsonOffset =
              fbb.writeString(object.capabilitiesJson);
          final telemetryJsonOffset = fbb.writeString(object.telemetryJson);
          final localIpOffset =
              object.localIp == null ? null : fbb.writeString(object.localIp!);
          final authTokenOffset = object.authToken == null
              ? null
              : fbb.writeString(object.authToken!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uniqueDeviceIdOffset);
          fbb.addOffset(2, deviceNameOffset);
          fbb.addOffset(3, statusNameOffset);
          fbb.addOffset(4, capabilitiesJsonOffset);
          fbb.addOffset(5, telemetryJsonOffset);
          fbb.addOffset(6, localIpOffset);
          fbb.addOffset(7, authTokenOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DeviceEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uniqueDeviceId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..deviceName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..statusName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..capabilitiesJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..telemetryJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..localIp = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..authToken = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DeviceEntity] entity fields to define ObjectBox queries.
class DeviceEntity_ {
  /// See [DeviceEntity.id].
  static final id =
      obx.QueryIntegerProperty<DeviceEntity>(_entities[0].properties[0]);

  /// See [DeviceEntity.uniqueDeviceId].
  static final uniqueDeviceId =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[1]);

  /// See [DeviceEntity.deviceName].
  static final deviceName =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[2]);

  /// See [DeviceEntity.statusName].
  static final statusName =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[3]);

  /// See [DeviceEntity.capabilitiesJson].
  static final capabilitiesJson =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[4]);

  /// See [DeviceEntity.telemetryJson].
  static final telemetryJson =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[5]);

  /// See [DeviceEntity.localIp].
  static final localIp =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[6]);

  /// See [DeviceEntity.authToken].
  static final authToken =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[7]);
}
