import 'dart:convert';
import '../../domain/models/matter_device.dart';
import '../models/device_entity.dart';
import '../repositories/device_repository.dart';

// objectbox.g.dart is generated by build_runner from device_entity.dart.
// Run: flutter pub run build_runner build --delete-conflicting-outputs
// ignore: depend_on_referenced_packages
import 'package:nexus_hub_app/objectbox.g.dart';

/// Production [DeviceRepository] backed by the local ObjectBox database.
///
/// Per the architecture whitepaper: "The UI communicates exclusively with a
/// local database cache. Pressing a UI switch instantly mutates the cache,
/// making the app feel zero-latency."
///
/// Receives the [Store] instance via constructor injection from the Riverpod
/// [objectboxStoreProvider] — see lib/core/objectbox_store_provider.dart.
class ObjectBoxDeviceDatasource implements DeviceRepository {
  final Box<DeviceEntity> _box;

  ObjectBoxDeviceDatasource(Store store) : _box = store.box<DeviceEntity>();

  @override
  Future<List<MatterDevice>> getDevices() async {
    return _box.getAll().map((e) => e.toDomain()).toList();
  }

  @override
  Future<void> updateDeviceState(
      String deviceId, Map<String, dynamic> patch) async {
    final q =
        _box.query(DeviceEntity_.uniqueDeviceId.equals(deviceId)).build();
    final entity = q.findFirst();
    q.close();
    if (entity == null) return;

    final existing =
        jsonDecode(entity.telemetryJson) as Map<String, dynamic>;
    existing.addAll(patch);
    entity.telemetryJson = jsonEncode(existing);
    _box.put(entity);
  }

  @override
  Future<void> provisionDevice(MatterDevice device) async {
    // @Unique(onConflict: ConflictStrategy.replace) handles upsert automatically.
    _box.put(DeviceEntity.fromDomain(device));
  }

  @override
  Future<void> removeDevice(String deviceId) async {
    final q =
        _box.query(DeviceEntity_.uniqueDeviceId.equals(deviceId)).build();
    final entity = q.findFirst();
    q.close();
    if (entity != null) _box.remove(entity.id);
  }
}
