import 'dart:convert';
import 'package:isar/isar.dart';
import '../../domain/models/matter_device.dart';

part 'isar_device.g.dart'; // Generated by: flutter pub run build_runner build

/// Isar-persisted device record.
///
/// Bridges between the Isar storage format and the domain [MatterDevice] model.
/// Telemetry (Map<String, dynamic>) is stored as a JSON string because Isar
/// does not natively support arbitrary maps.
///
/// To regenerate the schema after editing this file:
///   flutter pub run build_runner build --delete-conflicting-outputs
@collection
class IsarDevice {
  Id id = Isar.autoIncrement;

  /// Globally unique device identifier (MAC address or Matter Node ID).
  @Index(unique: true, replace: true)
  late String uniqueDeviceId;

  late String deviceName;

  /// DeviceStatus stored as its enum name string ('online', 'offline', etc.)
  @Enumerated(EnumType.name)
  late DeviceStatus status;

  late List<String> capabilities;

  /// JSON-encoded Map<String, dynamic> — Isar does not support dynamic maps.
  late String telemetryJson;

  /// Optional LAN IP for direct HTTP transport (Tasmota-style).
  String? localIp;

  // ── Conversions ───────────────────────────────────────────────────────────

  MatterDevice toDomain() => MatterDevice(
        uniqueDeviceId: uniqueDeviceId,
        deviceName: deviceName,
        status: status,
        capabilities: List<String>.from(capabilities),
        telemetry: telemetryJson.isNotEmpty
            ? Map<String, dynamic>.from(jsonDecode(telemetryJson) as Map)
            : {},
        localIp: localIp,
      );

  static IsarDevice fromDomain(MatterDevice d) => IsarDevice()
    ..uniqueDeviceId = d.uniqueDeviceId
    ..deviceName = d.deviceName
    ..status = d.status
    ..capabilities = List<String>.from(d.capabilities)
    ..telemetryJson =
        d.telemetry.isNotEmpty ? jsonEncode(d.telemetry) : '{}'
    ..localIp = d.localIp;
}
