// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/device_entity.dart';
import 'data/models/device_group_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 861110254133854312),
      name: 'DeviceEntity',
      lastPropertyId: const obx_int.IdUid(13, 8914213233770304369),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 597514898662851586),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8723696582219747134),
            name: 'uniqueDeviceId',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(1, 767293445575446884)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7623059609342789997),
            name: 'deviceName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7504549426938232851),
            name: 'statusName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7108638476595533374),
            name: 'capabilitiesJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2478131308966573234),
            name: 'telemetryJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 273300460829165690),
            name: 'localIp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6710299167213865616),
            name: 'authToken',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6994224725990469923),
            name: 'customName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3788933501037223962),
            name: 'powerRestoreModeStr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3569863789617618864),
            name: 'typeId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2091619496737755653),
            name: 'deviceType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 8914213233770304369),
            name: 'firmwareVersion',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1460955573890074879),
      name: 'DeviceGroupEntity',
      lastPropertyId: const obx_int.IdUid(4, 7996503302813182561),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4845781474436824501),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4017806205329500840),
            name: 'groupId',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(2, 143970839907561)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1770775257710283276),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7996503302813182561),
            name: 'deviceIdsJson',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1460955573890074879),
      lastIndexId: const obx_int.IdUid(2, 143970839907561),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DeviceEntity: obx_int.EntityDefinition<DeviceEntity>(
        model: _entities[0],
        toOneRelations: (DeviceEntity object) => [],
        toManyRelations: (DeviceEntity object) => {},
        getId: (DeviceEntity object) => object.id,
        setId: (DeviceEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceEntity object, fb.Builder fbb) {
          final uniqueDeviceIdOffset = fbb.writeString(object.uniqueDeviceId);
          final deviceNameOffset = fbb.writeString(object.deviceName);
          final statusNameOffset = fbb.writeString(object.statusName);
          final capabilitiesJsonOffset =
              fbb.writeString(object.capabilitiesJson);
          final telemetryJsonOffset = fbb.writeString(object.telemetryJson);
          final localIpOffset =
              object.localIp == null ? null : fbb.writeString(object.localIp!);
          final authTokenOffset = object.authToken == null
              ? null
              : fbb.writeString(object.authToken!);
          final customNameOffset = object.customName == null
              ? null
              : fbb.writeString(object.customName!);
          final powerRestoreModeStrOffset =
              fbb.writeString(object.powerRestoreModeStr);
          final typeIdOffset =
              object.typeId == null ? null : fbb.writeString(object.typeId!);
          final deviceTypeOffset = fbb.writeString(object.deviceType);
          final firmwareVersionOffset = fbb.writeString(object.firmwareVersion);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uniqueDeviceIdOffset);
          fbb.addOffset(2, deviceNameOffset);
          fbb.addOffset(3, statusNameOffset);
          fbb.addOffset(4, capabilitiesJsonOffset);
          fbb.addOffset(5, telemetryJsonOffset);
          fbb.addOffset(6, localIpOffset);
          fbb.addOffset(7, authTokenOffset);
          fbb.addOffset(8, customNameOffset);
          fbb.addOffset(9, powerRestoreModeStrOffset);
          fbb.addOffset(10, typeIdOffset);
          fbb.addOffset(11, deviceTypeOffset);
          fbb.addOffset(12, firmwareVersionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DeviceEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uniqueDeviceId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..deviceName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..statusName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..capabilitiesJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..telemetryJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..localIp = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..authToken = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..customName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20)
            ..powerRestoreModeStr =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 22, '')
            ..typeId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 24)
            ..deviceType = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 26, '')
            ..firmwareVersion = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '');

          return object;
        }),
    DeviceGroupEntity: obx_int.EntityDefinition<DeviceGroupEntity>(
        model: _entities[1],
        toOneRelations: (DeviceGroupEntity object) => [],
        toManyRelations: (DeviceGroupEntity object) => {},
        getId: (DeviceGroupEntity object) => object.id,
        setId: (DeviceGroupEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceGroupEntity object, fb.Builder fbb) {
          final groupIdOffset = fbb.writeString(object.groupId);
          final nameOffset = fbb.writeString(object.name);
          final deviceIdsJsonOffset = fbb.writeString(object.deviceIdsJson);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, groupIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, deviceIdsJsonOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DeviceGroupEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..groupId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..deviceIdsJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '');

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DeviceEntity] entity fields to define ObjectBox queries.
class DeviceEntity_ {
  /// See [DeviceEntity.id].
  static final id =
      obx.QueryIntegerProperty<DeviceEntity>(_entities[0].properties[0]);

  /// See [DeviceEntity.uniqueDeviceId].
  static final uniqueDeviceId =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[1]);

  /// See [DeviceEntity.deviceName].
  static final deviceName =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[2]);

  /// See [DeviceEntity.statusName].
  static final statusName =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[3]);

  /// See [DeviceEntity.capabilitiesJson].
  static final capabilitiesJson =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[4]);

  /// See [DeviceEntity.telemetryJson].
  static final telemetryJson =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[5]);

  /// See [DeviceEntity.localIp].
  static final localIp =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[6]);

  /// See [DeviceEntity.authToken].
  static final authToken =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[7]);

  /// See [DeviceEntity.customName].
  static final customName =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[8]);

  /// See [DeviceEntity.powerRestoreModeStr].
  static final powerRestoreModeStr =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[9]);

  /// See [DeviceEntity.typeId].
  static final typeId =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[10]);

  /// See [DeviceEntity.deviceType].
  static final deviceType =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[11]);

  /// See [DeviceEntity.firmwareVersion].
  static final firmwareVersion =
      obx.QueryStringProperty<DeviceEntity>(_entities[0].properties[12]);
}

/// [DeviceGroupEntity] entity fields to define ObjectBox queries.
class DeviceGroupEntity_ {
  /// See [DeviceGroupEntity.id].
  static final id =
      obx.QueryIntegerProperty<DeviceGroupEntity>(_entities[1].properties[0]);

  /// See [DeviceGroupEntity.groupId].
  static final groupId =
      obx.QueryStringProperty<DeviceGroupEntity>(_entities[1].properties[1]);

  /// See [DeviceGroupEntity.name].
  static final name =
      obx.QueryStringProperty<DeviceGroupEntity>(_entities[1].properties[2]);

  /// See [DeviceGroupEntity.deviceIdsJson].
  static final deviceIdsJson =
      obx.QueryStringProperty<DeviceGroupEntity>(_entities[1].properties[3]);
}
